/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './context/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-container':          '#c5fe00',
        'primary':                    '#f3ffcd',
        'primary-dim':                '#b9ef00',
        'primary-fixed':              '#c5fe00',
        'on-primary':                 '#4f6700',
        'on-primary-container':       '#485e00',
        'secondary-container':        '#454747',
        'on-secondary-container':     '#d0d0d0',
        'surface-container-lowest':   '#000000',
        'surface-container-low':      '#131313',
        'surface-container':          '#191919',
        'surface-container-high':     '#1f1f1f',
        'surface-container-highest':  '#262626',
        'surface-bright':             '#2c2c2c',
        'surface':                    '#0e0e0e',
        'surface-dim':                '#0e0e0e',
        'surface-variant':            '#262626',
        'surface-tint':               '#f3ffcd',
        'on-surface':                 '#ffffff',
        'on-surface-variant':         '#ababab',
        'on-background':              '#ffffff',
        'background':                 '#0e0e0e',
        'outline':                    '#757575',
        'outline-variant':            '#484848',
        'error':                      '#ff7351',
        'error-dim':                  '#d53d18',
        'error-container':            '#b92902',
        'on-error-container':         '#ffd2c8',
        'inverse-surface':            '#f9f9f9',
        'inverse-on-surface':         '#555555',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg:      '2rem',
        xl:      '3rem',
        full:    '9999px',
      },
      fontSize: {
        'display-lg': ['3.5rem',  { lineHeight: '0.95', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-md': ['2.5rem',  { lineHeight: '0.95', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg':['2rem',    { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md':['1.75rem', { lineHeight: '1.1',  letterSpacing: '-0.015em',fontWeight: '700' }],
        'title-lg':   ['1.25rem', { lineHeight: '1.4',  fontWeight: '700' }],
        'title-md':   ['1rem',    { lineHeight: '1.4',  fontWeight: '700' }],
        'body-lg':    ['1rem',    { lineHeight: '1.7',  fontWeight: '400' }],
        'body-md':    ['0.875rem',{ lineHeight: '1.6',  fontWeight: '400' }],
        'label-sm':   ['0.75rem', { lineHeight: '1.4',  fontWeight: '500', letterSpacing: '0.08em' }],
      },
      boxShadow: {
        'lime-glow':  '0 20px 50px rgba(197,254,0,0.2)',
        'lime-sm':    '0 8px 24px rgba(197,254,0,0.12)',
        'ambient':    '0 0 40px rgba(255,255,255,0.05)',
      },
      backgroundImage: {
        'lime-gradient': 'linear-gradient(135deg, #c5fe00, #b9ef00)',
      },
    },
  },
  plugins: [],
}
